movieapp/urls.py
from django.urls import path
from . import views

app_name='movieapp'

urlpatterns = [
    path('',views.index,name='index' ),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')

]

movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("movieapp.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movieapp/forms.py
from django import forms
from . models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .forms import MovieForm

# Create your views here.
from movieapp.models import Movie


def index(request):
    movie=Movie.objects.all()
    context={
        'movie_list':movie
    }

    return render(request,'index.html',context)

def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,'detail.html',{'movie':movie})

def add_movie(request):
    if request.method=="POST":
        name=request.POST.get('name')
        desc = request.POST.get('desc')
        year = request.POST.get('year')
        img = request.FILES["img"]
        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()

    return render(request,"add.html")


def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

templates/add.html
{% extends 'base.html' %}
{% block body %}


<div class="container-fluid ">
<div class="row">
<div class="col-md-6 offset-md-3">
  <form id="addmovie" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
  <h1>Add Movie</h1>
  <div class="form-group">
    <label for="name">Movie Name </label>
    <input type="text" class="form-control" id="name" name="name" placeholder="Enter Name">

  </div>
  <div class="form-group">
     <label for="year">Year </label>
    <input type="text" class="form-control" id="year" name="year" placeholder="Enter Year">
  </div>

    <div class="form-group">
     <label for="image">Image </label>
     <input type="file" id="image" name="img">
   </div>

  <div class="form-group">
     <label for="desc">Description </label>
    <input type="text" class="form-control" id="desc" name="desc" placeholder="Enter description">
  </div>
  <button type="submit" class="btn btn-success btn-block">Add</button>
</form>
</div>
</div>
</div>




<!--<div style="margin-top:100px">-->
<!--<form method="POST" enctype="multipart/form-data">-->
<!--  {% csrf_token %}-->
<!--    <input type="text" name="name" placeholder="Enter Name"><br>-->
<!--    <input type="text" name="desc" placeholder="Enter desc"><br>-->
<!--    <input type="file" name="img"><br>-->
<!--    <input type="text" name="year" placeholder="Enter Year"><br>-->
<!--    <input type="submit">-->

<!--</form>-->
<!--</div>-->
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">

</head>
<body>
 <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
          <a class="navbar-brand" href="{% url 'movieapp:index' %}">Movie Store
<!--            <img src="../images/logo1.png" width="70" height="40" alt="">-->
          </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
<!--        <div class="collapse navbar-collapse" id="navbarNav">-->
<!--          <ul class="nav navbar-nav ml-auto">-->
<!--            <li class="nav-item active">-->
<!--              <a class="nav-link" href="index.html">Home <span class="sr-only">(current)</span></a>-->
<!--            </li>-->

<!--            <li class="nav-item">-->
<!--              <a class="nav-link" href="signup.html">Sign Up</a>-->
<!--            </li>-->
<!--            <li class="nav-item">-->
<!--              <a class="nav-link" href="login.html">Login</a>-->
<!--            </li>-->

<!--          </ul>-->
<!--        </div>-->
      </nav>


{% block body %}
{% endblock %}


</body>
</html>

templates/delete.html
<form method="POST">
  {% csrf_token %}
  Do you want to delete?
  <input type="submit">
</form>

templates/detail.html
{% extends 'base.html' %}
{% block body %}

<div class="container-fluid" style="margin-top:12rem">
     <div class="row r1">
         <div class="image col-md-4" style="display:inline-block">
            <img src="{{movie.img.url}}" width="200" height="250" >
         </div>
        <div class="detail col-md-8" style="display:inline-block">
            <h4 style="color:white">{{movie.name}} </h4>
            <h6 style="color:white">{{movie.year}} </h6><br>
            <p style="color:white">{{movie.desc}}</p><br>
            <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">Edit</a>
            <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">delete</a>
        </div>
      </div>
</div>



<!--<div style="margin-top:100px">-->

<!--    <img src="{{movie.img.url}}" width="150" height="200">-->
<!--    <p style="color:white">{{movie.name}} </p>-->
<!--    <p style="color:white">{{movie.year}} </p>-->
<!--    <p style="color:white">{{movie.desc}}</p>-->
<!--    <a class="btn btn-primary" href="{% url 'movieapp:update' movie.id %}">Edit</a>-->
<!--    <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">delete</a>-->
<!--</div>-->

{% endblock %}

templates/edit.html
{% extends 'base.html' %}
{% block body %}

<div class="container-fluid edit">
<div class="row">
<div class="col-md-6 offset-md-3">
<form id="edit" method="post" enctype="multipart/form-data">
    <h1>Update</h1>
    {% csrf_token %}
    {{ form.as_p }}
    <br>
    <button type="submit" class="btn btn-success " >Update</button>
<!--    <input type="submit">-->
</form>
</div>
</div>
</div>










<!--<form method="post" enctype="multipart/form-data">-->
<!--    {% csrf_token %}-->
<!--    {{ form.as_p }}-->
<!--    <br>-->
<!--    <input type="submit">-->
<!--</form>-->
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block body %}

   <div class="container sl" style="margin-top:100px">
                <h1 id="heading">Available Movies</h1>
                 <div class="row">
                  {% for i in movie_list %}
                   <div class="col-sm-12 col-lg-4">
                     <div class="card">
                      <img class="card-img-top " src="{{i.img.url}}" height="250px"  alt="...">
                      <div class="card-body">
                        <h4 class="card-title">{{i.name}}</h4>
                        <h6 class="card-subtitle">{{i.year}}</h6><br>
                        <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-warning">View Details</a>
                      </div>
                     </div>
                   </div>
                  {% endfor %}

                 </div>
                </div>



<!-- <div style="margin-top:100px">-->
<!--     {% for i in movie_list %}-->
<!--     <img src="{{i.img.url}}" width="150" height="200">-->
<!-- <a href="{% url 'movieapp:detail' i.id %}"> {{i.name}}</a><br><br>-->
<!--{% endfor %}-->
<!-- </div>-->
{% endblock %}